/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as MainIndexRouteImport } from './routes/main/index'
import { Route as ExamplesPokemonRouteRouteImport } from './routes/examples/pokemon/route'
import { Route as ExamplesPokemonIndexRouteImport } from './routes/examples/pokemon/index'
import { Route as ExamplesPokemonIdIndexRouteImport } from './routes/examples/pokemon/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/main/',
  path: '/main/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesPokemonRouteRoute = ExamplesPokemonRouteRouteImport.update({
  id: '/examples/pokemon',
  path: '/examples/pokemon',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesPokemonIndexRoute = ExamplesPokemonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamplesPokemonRouteRoute,
} as any)
const ExamplesPokemonIdIndexRoute = ExamplesPokemonIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => ExamplesPokemonRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examples/pokemon': typeof ExamplesPokemonRouteRouteWithChildren
  '/main': typeof MainIndexRoute
  '/signup': typeof SignupIndexRoute
  '/examples/pokemon/': typeof ExamplesPokemonIndexRoute
  '/examples/pokemon/$id': typeof ExamplesPokemonIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/main': typeof MainIndexRoute
  '/signup': typeof SignupIndexRoute
  '/examples/pokemon': typeof ExamplesPokemonIndexRoute
  '/examples/pokemon/$id': typeof ExamplesPokemonIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/examples/pokemon': typeof ExamplesPokemonRouteRouteWithChildren
  '/main/': typeof MainIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/examples/pokemon/': typeof ExamplesPokemonIndexRoute
  '/examples/pokemon/$id/': typeof ExamplesPokemonIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/examples/pokemon'
    | '/main'
    | '/signup'
    | '/examples/pokemon/'
    | '/examples/pokemon/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/main' | '/signup' | '/examples/pokemon' | '/examples/pokemon/$id'
  id:
    | '__root__'
    | '/'
    | '/examples/pokemon'
    | '/main/'
    | '/signup/'
    | '/examples/pokemon/'
    | '/examples/pokemon/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamplesPokemonRouteRoute: typeof ExamplesPokemonRouteRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/': {
      id: '/main/'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/pokemon': {
      id: '/examples/pokemon'
      path: '/examples/pokemon'
      fullPath: '/examples/pokemon'
      preLoaderRoute: typeof ExamplesPokemonRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/pokemon/': {
      id: '/examples/pokemon/'
      path: '/'
      fullPath: '/examples/pokemon/'
      preLoaderRoute: typeof ExamplesPokemonIndexRouteImport
      parentRoute: typeof ExamplesPokemonRouteRoute
    }
    '/examples/pokemon/$id/': {
      id: '/examples/pokemon/$id/'
      path: '/$id'
      fullPath: '/examples/pokemon/$id'
      preLoaderRoute: typeof ExamplesPokemonIdIndexRouteImport
      parentRoute: typeof ExamplesPokemonRouteRoute
    }
  }
}

interface ExamplesPokemonRouteRouteChildren {
  ExamplesPokemonIndexRoute: typeof ExamplesPokemonIndexRoute
  ExamplesPokemonIdIndexRoute: typeof ExamplesPokemonIdIndexRoute
}

const ExamplesPokemonRouteRouteChildren: ExamplesPokemonRouteRouteChildren = {
  ExamplesPokemonIndexRoute: ExamplesPokemonIndexRoute,
  ExamplesPokemonIdIndexRoute: ExamplesPokemonIdIndexRoute,
}

const ExamplesPokemonRouteRouteWithChildren =
  ExamplesPokemonRouteRoute._addFileChildren(ExamplesPokemonRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamplesPokemonRouteRoute: ExamplesPokemonRouteRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
